version: '2'
services:
    db:
        container_name: {{cookiecutter.repo_name}}_db
        image: postgres 
        environment:
            - POSTGRES_DB={{cookiecutter.repo_name}}
            
    api:
        container_name: {{cookiecutter.repo_name}}_api
        build: .
        command: bash -c "source ~/.venvs/{{cookiecutter.repo_name}}venv/bin/activate && uwsgi --http :8000 --module {{cookiecutter.repo_name}}.wsgi --socket :8001" 
        env_file:
            - production.env
        environment:
            - PYTHONUNBUFFERED=1
            - DEBUG
            - ADMIN
            - PRODUCTION
        volumes:
            - .:/code
            - ./static:/static
        ports:
            - "8000:8000"
            - "8001:8001"
        depends_on:
            - db

    server:
        container_name: {{cookiecutter.repo_name}}_server
        build: .dockerfiles/nginx
        ports:
            - "80:80"
        volumes:
           - ./static:/static
        depends_on:
            - api
