image: docker

stages:
  - lint
  - unit-test

services:
  - docker:dind

before_script:
  - apk add --no-cache python3 make
  - pip3 install flake8 docker-compose
  - cp -u production.env.template production.env

Lint:
  stage: lint
  script:
    - flake8

Unit Test:
  stage: unit-test
  script:
    - make test
